# Generated by Django 5.2.8 on 2025-12-15 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_choice', models.CharField(choices=[('NORMAL30', 'NORMAL30'), ('NORMAL60', 'NORMAL60'), ('FLAGSHIP30', 'FLAGSHIP30'), ('FLAGSHIP60', 'FLAGSHIP60'), ('PREMIUM30', 'PREMIUM30'), ('PREMIUM60', 'PREMIUM60')], default='NORMAL60', max_length=20)),
                ('subscription_phase', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('meal_history', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
