# Generated by Django 5.2.9 on 2025-12-29 18:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_customerhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerHistory',
            new_name='MealHistory',
        ),
    ]
