# Generated by Django 5.2.9 on 2026-01-01 11:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_rename_customerhistory_mealhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MealHistory',
            new_name='SubscriptionHistory',
        ),
    ]
