# Generated by Django 5.2.8 on 2025-11-30 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('meal_balance', models.IntegerField()),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('profile_updated_at', models.DateTimeField(auto_now=True)),
                ('user_status_active', models.BooleanField(default=True)),
                ('lunch_status_active', models.BooleanField(default=True)),
                ('dinner_status_active', models.BooleanField(default=True)),
                ('default_service_choice', models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], max_length=20)),
                ('default_meal_choice', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DinnerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(auto_now_add=True)),
                ('meal_choice', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20)),
                ('meal_num_used', models.IntegerField()),
                ('service_choice', models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dinner_records', to='Customers.customer')),
            ],
        ),
        migrations.CreateModel(
            name='LunchRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField(auto_now_add=True)),
                ('meal_choice', models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20)),
                ('meal_num_used', models.IntegerField()),
                ('service_choice', models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lunch_records', to='Customers.customer')),
            ],
        ),
    ]
