# Generated by Django 5.2.8 on 2025-11-30 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='low_balance_status_active',
            field=models.BooleanField(default=False),
        ),
    ]
