# Generated by Django 5.2.8 on 2025-12-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0002_customer_low_balance_status_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_choice',
            field=models.CharField(choices=[('NORMAL30', 'NORMAL30'), ('NORMAL60', 'NORMAL60'), ('FLAGSHIP30', 'FLAGSHIP30'), ('FLAGSHIP60', 'FLAGSHIP60'), ('PREMIUM30', 'PREMIUM30'), ('PREMIUM60', 'PREMIUM60')], default='NORMAL60', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_meal_choice',
            field=models.CharField(choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='VEG', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='DineIn', max_length=20),
        ),
    ]
