# Generated by Django 5.2.8 on 2025-12-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0003_customer_subscription_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinnerrecord',
            name='decrement_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lunchrecord',
            name='decrement_done',
            field=models.BooleanField(default=False),
        ),
    ]
