# Generated by Django 5.2.8 on 2025-12-01 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0004_dinnerrecord_decrement_done_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerrecord',
            name='for_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='for_date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dinnerrecord',
            constraint=models.UniqueConstraint(fields=('customer', 'for_date'), name='unique_dinner_per_customer_per_day'),
        ),
        migrations.AddConstraint(
            model_name='lunchrecord',
            constraint=models.UniqueConstraint(fields=('customer', 'for_date'), name='unique_lunch_per_customer_per_day'),
        ),
    ]
