# Generated by Django 5.2.8 on 2025-12-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0005_alter_dinnerrecord_for_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='FLAGSHIP_MENU_DINNER_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], default='VEG', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='FLAGSHIP_MENU_LUNCH_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], default='VEG', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='FLAGSHIP_MENU_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='PANEER', max_length=20),
        ),
        migrations.AddField(
            model_name='dinnerrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dinnerrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lunchrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lunchrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
    ]
