# Generated by Django 5.2.8 on 2025-12-01 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0006_customer_flagship_menu_dinner_default_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='FLAGSHIP_MENU_DINNER_default_choice',
            new_name='PREMIUM_MENU_DINNER_default_choice',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='FLAGSHIP_MENU_LUNCH_default_choice',
            new_name='PREMIUM_MENU_LUNCH_default_choice',
        ),
    ]
