# Generated by Django 5.2.8 on 2025-12-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0007_rename_flagship_menu_dinner_default_choice_customer_premium_menu_dinner_default_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='FLAGSHIP_MENU_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='NONE', max_length=20),
        ),
    ]
