# Generated by Django 5.2.8 on 2025-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0008_alter_customer_flagship_menu_default_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_DINNER_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_LUNCH_default_choice',
            field=models.CharField(choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], default='NONE', max_length=20),
        ),
    ]
