# Generated by Django 5.2.8 on 2025-12-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0009_alter_customer_premium_menu_dinner_default_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='FLAGSHIP_MENU_default_choice',
        ),
        migrations.AddField(
            model_name='customer',
            name='FLAGSHIP_MENU_DINNER_default_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='FLAGSHIP_MENU_LUNCH_default_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_DINNER_default_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_LUNCH_default_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
    ]
