# Generated by Django 5.1.6 on 2025-12-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0010_remove_customer_flagship_menu_default_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_meal_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='VEG', max_length=20),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='meal_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='meal_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20),
        ),
    ]
