# Generated by Django 5.1.6 on 2025-12-02 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0011_customer_password_alter_customer_default_meal_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='password',
        ),
    ]
