# Generated by Django 5.1.6 on 2025-12-02 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0012_remove_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
