# Generated by Django 5.2.8 on 2025-12-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0014_rename_user_status_active_customer_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_status_active',
            field=models.BooleanField(default=True),
        ),
    ]
