# Generated by Django 5.2.8 on 2025-12-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0015_customer_user_status_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='default_service_choice',
            new_name='default_dinner_service_choice',
        ),
        migrations.AddField(
            model_name='customer',
            name='default_lunch_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='DineIn', max_length=20),
        ),
    ]
