# Generated by Django 5.2.8 on 2025-12-12 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0016_rename_default_service_choice_customer_default_dinner_service_choice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='low_balance_status_active',
            new_name='paused_subscription',
        ),
    ]
