# Generated by Django 5.2.8 on 2025-12-12 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0017_rename_low_balance_status_active_customer_paused_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinnerrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
    ]
