# Generated by Django 5.2.8 on 2025-12-15 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0018_alter_dinnerrecord_meal_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscription_phase',
            field=models.IntegerField(default=1),
        ),
    ]
