# Generated by Django 5.1.6 on 2025-12-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0019_customer_subscription_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_meal_choice',
            field=models.CharField(choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], default='NONE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('NONE', 'NONE'), ('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], default='NONE', max_length=20, null=True),
        ),
    ]
