# Generated by Django 5.2.9 on 2025-12-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0020_alter_customer_default_meal_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='FLAGSHIP_MENU_DINNER_default_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='FLAGSHIP_MENU_LUNCH_default_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_DINNER_default_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='PREMIUM_MENU_LUNCH_default_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_dinner_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_lunch_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_meal_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='subscription_choice',
            field=models.CharField(choices=[('NORMAL30', 'NORMAL30'), ('NORMAL60', 'NORMAL60'), ('FLAGSHIP30', 'FLAGSHIP30'), ('FLAGSHIP60', 'FLAGSHIP60'), ('PREMIUM30', 'PREMIUM30'), ('PREMIUM60', 'PREMIUM60')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='dinnerrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='FLAGSHIP_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='PREMIUM_choice',
            field=models.CharField(blank=True, choices=[('PANEER', 'PANEER'), ('MUSHROOM', 'MUSHROOM'), ('CHICKEN', 'CHICKEN'), ('EGG', 'EGG'), ('PRAWN', 'PRAWN'), ('FISH', 'FISH'), ('VEG', 'VEG')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='lunchrecord',
            name='meal_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
    ]
