# Generated by Django 5.2.9 on 2026-01-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0021_alter_customer_flagship_menu_dinner_default_choice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='default_sunday_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dinnerrecord',
            name='sunday_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='lunchrecord',
            name='sunday_choice',
            field=models.CharField(blank=True, choices=[('VEG', 'VEG'), ('NON-VEG', 'NON-VEG')], max_length=20, null=True),
        ),
    ]
