# Generated by Django 5.2.9 on 2026-01-02 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0022_customer_default_sunday_choice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinnerrecord',
            name='sunday_choice',
        ),
    ]
