# Generated by Django 5.2.9 on 2026-01-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customers', '0023_remove_dinnerrecord_sunday_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='default_dinner_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='DineIn', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='default_lunch_service_choice',
            field=models.CharField(choices=[('DineIn', 'DineIn'), ('PickUp', 'PickUp'), ('Delivery', 'Delivery'), ('Cancel', 'Cancel')], default='DineIn', max_length=20),
        ),
    ]
